### ISSUE TITLE
Wrong optional / types

### ISSUE THREAD

**Issue by PabstMirror** [acemod/arma3-wiki#3008]
- configProperties
[arg condition] typ: Unknown, opt: false
`condition: String - (Optional, default "true")`

- selectionPosition (Syntax 2)
[arg returnMode] typ: Unknown, opt: false
`returnMode: String - (Optional, default "FirstPoint") can be one of:`

- lineIntersectsSurfaces
[arg LOD1] typ: Unknown, opt: false
`LOD1: String - (Optional, default "VIEW") primary LOD to look for intersection. Can be one of:`

- insert (Syntax 1)
[arg onlyIfUnique] typ: Boolean, opt: false 
`onlyIfUnique: Boolean - only insert if the value is unique in the array, like pushBackUnique`
wiki wrong I guess? 

- createTrigger
[arg makeGlobal] typ: Unknown, opt: false
`makeGlobal: Boolean - (Optional - default true) locality flag`

**Comment by BrettMayson** [comment]
I'm trying to work on a branch that would be much better at determining things accurately, and capturing a lot more info too, but the wiki is too inconsistent. Every time I run it, it only gets a command or two in before it can't parse something, usually requiring wiki changes 

I don't have the time to fix everything myself, and when I posted about needing help in the future some people were interested, when I posted I was ready for help there was much less interest

**Comment by PabstMirror** [comment]
Would it be ok to just hardcode some of these with unusual arg blocks?

**Comment by BrettMayson** [comment]
I suppose that's fine for now, if it is just a few that need it
